export const NAMESPACE = 'SIMULATOR_'

export const SET_INTERNAL_DATA = `${NAMESPACE}SET_INTERNAL_DATA`
export const SET_EXTERNAL_DATA = `${NAMESPACE}SET_EXTERNAL_DATA`
export const SET_EXTERNAL_NODE_DATA = `${NAMESPACE}SET_EXTERNAL_NODE_DATA`
