export const SETUP_SET_QUERY = 'SETUP_SET_QUERY'
export const SETUP_SET_AS_PATH = 'SETUP_SET_AS_PATH'
export const SETUP_SET_URL_VARS = 'SETUP_SET_URL_VARS'
export const SETUP_SET_LOCALES = 'SETUP_SET_LOCALES'
export const SETUP_SET_ROUTES = 'SETUP_SET_ROUTES'
export const SETUP_SET_STRINGS = 'SETUP_SET_STRINGS'
export const SETUP_SET_LOCAL_STORAGE = 'SETUP_SET_LOCAL_STORAGE'

export const QBMIDI_SET_LINKS = 'QBMIDI_SET_LINKS'
