import React from 'react'
import PropTypes from 'prop-types'
import NProgress from 'nprogress'
import Router from 'next/router'
import Head from 'src/components/head'
import Header from 'src/components/header'
import Footer from 'src/components/footer'

class App extends React.Component {
	componentDidMount() {
		// hookup nprogress
		Router.router.events.on('routeChangeStart', NProgress.start)
		Router.router.events.on('routeChangeComplete', NProgress.done)
		Router.router.events.on('routeChangeError', NProgress.done)
	}

	componentWillUnmount() {
		// unhook nprogress
		Router.router.events.off('routeChangeStart', NProgress.start)
		Router.router.events.off('routeChangeComplete', NProgress.done)
		Router.router.events.off('routeChangeError', NProgress.done)
	}

	render() {
		const {
			propsHead,
			propsHeader,
			propsFooter,
			children
		} = this.props
		return (
			<div className="root app">
				<style jsx>{`
					/* This stylesheet generated by Transfonter (https://transfonter.org) on August 4, 2017 2:45 PM */
					@font-face { font-family: 'Brandon Text'; src: url('/static/fonts/BrandonText-Medium.eot'); src: url('/static/fonts/BrandonText-Medium.eot?#iefix') format('embedded-opentype'),url('/static/fonts/BrandonText-Medium.woff2') format('woff2'),url('/static/fonts/BrandonText-Medium.woff') format('woff'),url('/static/fonts/BrandonText-Medium.ttf') format('truetype'); font-weight: 500; font-style: normal; }
					@font-face { font-family: 'Brandon Text'; src: url('/static/fonts/BrandonText-Regular.eot'); src: url('/static/fonts/BrandonText-Regular.eot?#iefix') format('embedded-opentype'),url('/static/fonts/BrandonText-Regular.woff2') format('woff2'),url('/static/fonts/BrandonText-Regular.woff') format('woff'),url('/static/fonts/BrandonText-Regular.ttf') format('truetype'); font-weight: normal; font-style: normal; }
					@font-face { font-family: 'Brandon Text'; src: url('/static/fonts/BrandonText-Bold.eot'); src: url('/static/fonts/BrandonText-Bold.eot?#iefix') format('embedded-opentype'),url('/static/fonts/BrandonText-Bold.woff2') format('woff2'),url('/static/fonts/BrandonText-Bold.woff') format('woff'),url('/static/fonts/BrandonText-Bold.ttf') format('truetype'); font-weight: bold; font-style: normal; }

					:global(html),
					:global(body) {
						margin: 0;
						font-family: 'Brandon Text', sans-serif;
						font-size: 16px;
						line-height: 1.5;
					}
					:global(*){
						box-sizing: border-box;
					}
					:global(a) {
						color: inherit;
					}
					.root {
						position: fixed;
						height: 100vh;
						width: 100vw;
						display: grid;
						grid-template-columns: 1fr;
						grid-template-rows: 3rem auto 2rem;
					}
				`}</style>
				<Head {...propsHead}/>
				<Header {...propsHeader}/>
				{children}
				<Footer {...propsFooter}/>
			</div>
		)
	}
}

App.defaultProps = {
	propsHead   : Head.defaultProps,
	propsHeader : Header.defaultProps,
	propsFooter : Footer.defaultProps
}

App.propTypes = {
	propsHead   : PropTypes.shape(Head.propTypes),
	propsHeader : PropTypes.shape(Header.propTypes),
	propsFooter : PropTypes.shape(Footer.propTypes)
}

export default App
