export const NAMESPACE = 'FLOW_EDITOR_'

export const SET_NODE_DEFINITIONS = `${NAMESPACE}SET_NODE_DEFINITIONS`
export const SET_CATEGORY_DEFINITIONS = `${NAMESPACE}SET_CATEGORY_DEFINITIONS`
export const SET_CONSTANT_DEFINITIONS = `${NAMESPACE}SET_CONSTANT_DEFINITIONS`
export const SET_DISPLAY_ADVANCED_NODES = `${NAMESPACE}SET_DISPLAY_ADVANCED_NODES`
export const TOGGLE_FOLDED_CATEGORY = `${NAMESPACE}TOGGLE_FOLDED_CATEGORY`
export const REGISTER_GET_DROP_AREA_RECT = `${NAMESPACE}REGISTER_GET_DROP_AREA_RECT`

export const SET_SOURCE = `${NAMESPACE}SET_SOURCE`
export const ADD_INSTANCE = `${NAMESPACE}ADD_INSTANCE`
export const UPDATE_INSTANCE_NAME = `${NAMESPACE}UPDATE_INSTANCE_NAME`
export const UPDATE_INSTANCE_POSITION = `${NAMESPACE}UPDATE_INSTANCE_POSITION`
export const REMOVE_INSTANCE = `${NAMESPACE}REMOVE_INSTANCE`

export const SET_INSTANCE_PARAMETER = `${NAMESPACE}SET_INSTANCE_PARAMETER`
export const ADD_INSTANCE_PARAMETER_ITEM = `${NAMESPACE}ADD_INSTANCE_PARAMETER_ITEM`
export const REMOVE_INSTANCE_PARAMETER_ITEM = `${NAMESPACE}REMOVE_INSTANCE_PARAMETER_ITEM`

export const HIGHLIGHT_INSTANCE_PARAMETER_DROP_AREA = `${NAMESPACE}HIGHLIGHT_INSTANCE_PARAMETER_DROP_AREA`

export const SET_IS_DRAGGING_OUTLET = `${NAMESPACE}SET_IS_DRAGGING_OUTLET`

export const SET_OUTLET_TRANSFER_DRAG_METHODS = `${NAMESPACE}SET_OUTLET_TRANSFER_DRAG_METHODS`
