export const NAMESPACE = 'FLOW_EDITOR_'
export const SET_NODE_DEFINITIONS = `${NAMESPACE}SET_NODE_DEFINITIONS`
export const SET_CATEGORY_DEFINITIONS = `${NAMESPACE}SET_CATEGORY_DEFINITIONS`
export const SET_DISPLAY_ADVANCED_NODES = `${NAMESPACE}SET_DISPLAY_ADVANCED_NODES`
export const TOGGLE_FOLDED_CATEGORY = `${NAMESPACE}TOGGLE_FOLDED_CATEGORY`
