export const NAMESPACE = 'FLOW_EDITOR_'
export const SET_NODE_DEFINITIONS = `${NAMESPACE}SET_NODE_DEFINITIONS`
export const SET_CATEGORY_DEFINITIONS = `${NAMESPACE}SET_CATEGORY_DEFINITIONS`
export const SET_DISPLAY_ADVANCED_NODES = `${NAMESPACE}SET_DISPLAY_ADVANCED_NODES`
export const TOGGLE_FOLDED_CATEGORY = `${NAMESPACE}TOGGLE_FOLDED_CATEGORY`
export const REGISTER_GET_DROP_AREA_RECT = `${NAMESPACE}REGISTER_GET_DROP_AREA_RECT`

export const SET_SOURCE = `${NAMESPACE}SET_SOURCE`
export const ADD_INSTANCE = `${NAMESPACE}ADD_INSTANCE`
export const REMOVE_INSTANCE = `${NAMESPACE}REMOVE_INSTANCE`
